name: tag

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: version-get
        name: Get version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - id: version-display
        name: Display version
        run: echo ${{ env.VERSION }}

      - id: version-check
        name: Check version format
        run: |
          if [[ "${{ env.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: "Link the workflow to Yontrack"
        if: steps.version-check.outputs.valid == 'true'
        uses: nemerosa/ontrack-github-actions-cli-library/ontrack-cli-workflow-build@v1.0.2
        with:
          project: ontrack-jenkins-cli-pipeline
          yontrack-url: ${{ vars.ONTRACK_URL }}
          yontrack-token: ${{ secrets.ONTRACK_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release label
        if: steps.version-check.outputs.valid == 'true'
        run: |
          yontrack build set-property release ${{ env.VERSION }}

      - name: GitHub release
        if: steps.version-check.outputs.valid == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yontrack build changelog export \
            --from-promotion GOLD \
            --to $YONTRACK_BUILD_ID \
            --format markdown > .yontrack.log.md
          gh release create ${{ env.VERSION }} --title "${{ env.VERSION }}" --notes ""

      - name: Yontrack release
        if: steps.version-check.outputs.valid == 'true'
        run: |
          yontrack promote -l GOLD -d "GitHub release created"
